VisitListMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VisitListMVC.Models;

namespace VisitListMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VisitListMVC/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using VisitListMVC.Models.Visits;

namespace VisitListMVC.Controllers
{
    public class MapController : Controller
    {
        public VisitInventory visitList = new();

        public IActionResult Map()
        {
            visitList = VisitService.GetInventory();
            return View(visitList);
        }
    }
}

VisitListMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenue sur VisitList</h1>
 </div>
<h2>Vous pouvez vous rendre sur ces pages :</h2>
<ul>
    <li>
        <a asp-controller="Visits" asp-action="Visits">Les visites</a>
    </li>
    <li>
        <a asp-controller="Map" asp-action="Map">La carte</a>
    </li>
</ul>